name: Semgrep Scan

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep Static Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep scan --config auto --verbose
      - run: semgrep scan --config auto --sarif > semgrep-results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
